version: '3'

services:
  desa:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    working_dir: /opt/app
    container_name: "desa"
    volumes:
      - "./:/opt/app"
      - /opt/app/node_modules